# Original template: https://github.com/jekyll/jekyll/blob/master/lib/site_template/_config.yml

title: Kibeom Kim
email: kk1674@nyu.edu

baseurl: "/"
url: "https://kkimdev.github.io"

github_username:  kkimdev
linkedin_username: kkimdev
youtube_username: channel/UCFjh-t8vgQxkxAvhOd1byzw/
facebook_username: kkimdev

markdown: kramdown
theme: minima

google_analytics: UA-120931282-1

plugins:
  - jekyll-feed
  - jekyll-redirect-from

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: posts
      category: posts
